name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

# Add these permission settings
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        working-directory: ./data
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build site
        working-directory: ./data
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data/_site
          publish_branch: gh-pages  # deploying branch
